---
title: "功能指标相关性分析"
author: "ruc isbd"
date: '2022-09-14'
always_allow_html: yes
tables: yes
output:
  pdf_document:
    includes:
      in_header: "../library/header.tex"
    keep_tex: yes
    extra_dependencies: "subfig"
    latex_engine: xelatex
knit: (function(inputFile, encoding) {
      out_dir <- "reports";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
---
```{r header,echo=FALSE,results='hide',warning = FALSE,message = FALSE}
knitr::opts_chunk$set(
  warning = FALSE, # show warnings during codeNbook generation
  message = FALSE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = FALSE,  # show R code
  paged.print=FALSE,
  fig.pos = 'H', 
 out.width = "100%"
)
library(showtext)
showtext_auto()
box::use(../library/utils[...])
box::use(r/core[...])
box::use(tidyr[...])
box::use(kableExtra[...])
box::use(dplyr[...])
box::use(knitr[...])
box::use(ppcor[...])
# author tufuyi
```

```{r}
reg.sig<-function(x){
  x<-as.numeric(x)
  sig <- rep("",length(x))
  sig[which(x<0.1)] <- "."
  sig[which(x<0.05)] <- "*"
  sig[which(x<0.01)] <- "**"
  sig[which(x<0.001)] <- "***"
  return(sig)
}

cross.reg<-function(sample,score_name = "score",Fac_levels = NULL){
  sample <- sample%>%select(Age,Gender,score=all_of(score_name),Fac = Value)%>%drop_na(Age,Gender,score,Fac)%>%filter(Age >= 25 & Age <= 89)
  sample$AgeFactor <- case_when(
     (sample$Age>=25 & sample$Age <= 39) ~ "25-39",
     (sample$Age>=40 & sample$Age <= 59) ~ "40-59",
     (sample$Age>=60 & sample$Age <= 74) ~ "60-74",
     (sample$Age>=75 & sample$Age <= 89) ~ "75-89")
  if(is.null(Fac_levels)){
    sample$Fac <- ordered(sample$Fac)
  }
  else{
    sample$Fac <- ordered(sample$Fac,levels = Fac_levels)
  }
  if(score_name == "score"){
    a<-aov(score~Fac+Age+Gender,data=sample)
    t <- matrix(summary(a))[[1]][1:3,5]
    #t[which(t!=0)] <- round(t[which(t!=0)],digits = 5)
    #t[which(t==0)]<-"<1e-16"
    return(t)
  }
  
  if(score_name == "score.D"|score_name == "score.D2"){
    s <- summary(polr(ordered(score)~Fac+AgeFactor+Gender, method = "logistic", data=sample,Hess=TRUE))
    t<-round(s$coefficients[,c(1,4)],digits = 3)
    sigs <- reg.sig(t[,2])
    t<-cbind(t,sigs)
    colnames(t) <- c("估计量","P值","显著性")
    return(t)
  }
}

process.in <- function(sample,dim_name){
  if(dim_name == "F3"){
    sample$Value <- case_when(
  (sample$Value=="非常宽裕" | sample$Value=="比较宽裕") ~ "宽裕",
  (sample$Value=="比较困难" | sample$Value=="非常困难") ~ "困难",
  (sample$Value=="基本够用") ~ "基本够用")
  }
  else if(dim_name == "H1"){
    sample$Value <- case_when(
  (sample$Value=="市/县城的中心城区" | sample$Value=="市/县城的边缘城区") ~ "城市",
  (sample$Value=="市/县城的城乡结合部" | sample$Value=="市/县城区以外的镇" | sample$Value=="农村") ~ "农村")
  }
  else if(dim_name == "D7"){
    sample$Value <- case_when(
  (sample$Value=="非常方便" | sample$Value=="比较方便") ~ "方便",
  (sample$Value=="不太方便" | sample$Value=="很不方便") ~ "不方便",
  (sample$Value=="一般") ~ "一般")
  }
  return(sample)
}

Fac_level_choice <- function(dim_name){
  Fac_levels <- NULL
  if(dim_name == "F3"){
    Fac_levels <- c("困难","基本够用","宽裕")
  }
  else if(dim_name == "H1"){
    Fac_levels <- c("农村","城市")
  }
  else if(dim_name == "D7"){
    Fac_levels <- c("不方便","一般","方便")
  }
  else if(dim_name == "A5_new"){
    Fac_levels <- c("文盲","初等教育","中等教育","高等教育")
  }
  else if(dim_name == "D11_D"){
    Fac_levels <- c("不符合","符合")
  }
  else if(dim_name == "G2_new"){
    Fac_levels <- c("独居","不独居")
  }
  Fac_levels
}

table.aov<-function(data,dim_name,Ch_name,caption){
  n_dims <- length(dim_name)
  pvalues <- matrix(0,ncol = 3, nrow = n_dims)
  Fac_levels <- NULL
  for(i in 1:n_dims){
    datalist$updatesample(data,dim_name[i])
    sample <- process.in(datalist$sample,dim_name[i])
    Fac_levels <- Fac_level_choice(dim_name[i])
    pvalues[i,] <- cross.reg(sample,Fac_levels = Fac_levels)
  }
  tab <- data.frame(变量名=Ch_name,pvalues)
  colnames(tab)[2:4] <- c("X1","X2","X3")
  tab <- tab%>%arrange(X1)
  colnames(tab)[2:4] <- c("p值","p值(年龄)","p值(性别)")
  for(i in 2:3){
    tab[which(tab[,i]<1e-230),i] <- "<1e-230"
  }
  tab[which(tab[,4]<1e-20),4] <- "<1e-20"
  kbl(tab,caption = caption)%>%kable_styling(position = "center",latex_options = "hold_position")
}

table.spearman<-function(data,dim_name,Ch_name,caption,score_name = "score"){
  n_dims <- length(dim_name)
  pvalues <- matrix(0,ncol = 6, nrow = n_dims)
  Fac_levels <- NULL
  for(i in 1:n_dims){
    datalist$updatesample(data,dim_name[i])
    sample <- process.in(datalist$sample,dim_name[i])
    sample <- sample%>%dplyr::select(Age,Gender,score=all_of(score_name),Fac = Value)%>%drop_na(Age,Gender,score,Fac)%>%filter(Age >= 25 & Age <= 89)
    Fac_levels <- Fac_level_choice(dim_name[i])
    sample$Fac <- factor(sample$Fac,levels = Fac_levels)
    levels(sample$Gender) <- c(2,1)
    levels(sample$Fac) <- 1:length(unique(sample$Fac))
    sample <- apply(sample,2,as.numeric)
    p <- pcor(sample,method = "spearman")
    pvalues[i,c(1,3,5)] <- round(p$estimate[c(4,1,2),3],digits = 5)
    p_temp <- p$p.value[c(4,1,2),3]
    p_temp[which(p_temp==0)]<-"<1e-200"
    pvalues[i,c(2,4,6)] <- p_temp
  }
  tab <- data.frame(变量名=Ch_name,pvalues)
  colnames(tab)[2:7] <- paste0("X",1:6)
  tab <- tab%>%arrange(X2)
  colnames(tab)[2:7] <- c("Spearman秩相关系数","p值",
                          "Spearman秩相关系数(年龄)","p值(年龄)",
                          "Spearman秩相关系数(性别)","p值(性别)")
  kbl(tab,caption = caption)%>%kable_styling(position = "center",latex_options = c("hold_position","scale_down"))
}

table.aov.one<-function(data,dim_name,Ch_name,caption){
  n_dims <- length(dim_name)
  Fac_levels <- NULL
  datalist$updatesample(data,dim_name[1])
  sample <- process.in(datalist$sample,dim_name[1])
  Fac_levels <- Fac_level_choice(dim_name[1])
  data_aov <- sample%>%select(ID,Age,Gender,score,Value)
  data_aov$Value <- ordered(data_aov$Value,levels = Fac_levels)
  colnames(data_aov) <- c("ID","年龄","性别","score",Ch_name[1])
  for(i in 2:n_dims){
    datalist$updatesample(data,dim_name[i])
    sample <- process.in(datalist$sample,dim_name[i])
    Fac_levels <- Fac_level_choice(dim_name[i])
    sample_temp <- sample%>%select(ID,Value)
    sample_temp$Value <- ordered(sample_temp$Value,levels = Fac_levels)
    colnames(sample_temp)[2] <- Ch_name[i]
    data_aov <- data_aov%>%full_join(sample_temp,by = "ID")
  }
  
  data_aov$年龄 <- case_when(
     (data_aov$年龄>=25 & data_aov$年龄 <= 39) ~ "25-39",
     (data_aov$年龄>=40 & data_aov$年龄 <= 59) ~ "40-59",
     (data_aov$年龄>=60 & data_aov$年龄 <= 74) ~ "60-74",
     (data_aov$年龄>=75 & data_aov$年龄 <= 89) ~ "75-89")
  
  #colnames(data_aov)[5:ncol(data_aov)] <- dim_name
  #print(colnames(data_aov))
  data_aov <- data_aov%>%drop_na()%>%select(-ID)
  a<-aov(score~.,data=data_aov)
  pvalues <- matrix(summary(a))[[1]][1:(n_dims+2),5]

  tab <- data.frame(变量名=rownames(matrix(summary(a))[[1]])[1:(n_dims+2)],pvalues)
  tab <- tab%>%arrange(pvalues)
  tab[which(tab[,2]<1e-230),2] <- "<1e-230"
  colnames(tab)[2] <- c("p值")
  kbl(tab,caption = caption)%>%kable_styling(position = "center",latex_options = "hold_position")
}
```


```{r output}
dimnames <- c("F3","H1","A5_new","D11_D","D7","G2_new")
names <- c("自报经济情况","居住地","教育程度","健康意识","看病方便程度","是否独居")
table.aov(datalist$BJ_data,dimnames,names,"各验证指标p值表格(方差分析)")
#table.spearman(datalist$BJ_data,dimnames,names,"各验证指标p值表格(Spearman秩相关系数)")
```

```{r output4}
dimnames <- c("A5_new","D11_D","H1","G2_new","F3","D7")
names <- c("教育程度","健康意识","居住地","是否独居","自报经济情况","看病方便程度")
table.aov.one(datalist$BJ_data,dimnames,names,"指标汇总方差分析p值表格")
```
